language: node_js
node_js: 
  - "stable"
script:
  - yarn test
  - yarn predeploy
  - yarn deploy

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master